Bug 2050391: ztp: delete wave annotation from the policy-wrapped CRs
openshift-kni/cnf-features-deploy pull request #1004
Opened 2022-03-09 19:42 UTC by Missxiaoguo

Strip the wave annotation from the built CR after the wave is
assigned to the policy.

Signed-off-by: Angie Wang <angwang@redhat.com>

2022-03-09 19:42 UTC, Missxiaoguo commented
/hold
Testing is in progress

2022-03-10 15:31 UTC, serngawy requested changes
Its not right to set the annotation then remove it by code. As enduser I expect to see what i set in the source CRs. Please, add the wave annotation to the policies and remove it from the source-crs.

2022-03-10 18:57 UTC, Missxiaoguo commented
/unhold

2022-03-10 18:57 UTC, Missxiaoguo commented
/bugzilla refresh

2022-03-10 20:04 UTC, lack commented
> Its not right to set the annotation then remove it by code. As enduser I expect to see what i set in the source CRs. Please, add the wave annotation to the policies and remove it from the source-crs.

The problem with this approach is that it requires that customers create the right values in their PGTs.  The benefit of shipping these in the source-crs is that they are completely invisible to the customer (unless they introduce a mismatch).

Maybe longer-term we need to figure out a better way to more global policy-based things like this in a way such that customers don't have to change their PGTs to take advantage of them.

2022-03-10 21:22 UTC, lack commented
/lgtm

2022-03-10 22:00 UTC, merged

2022-03-10 22:09 UTC, Missxiaoguo commented
/cherry-pick release-4.10

2022-03-11 14:31 UTC, Missxiaoguo commented
/cherry-pick release-4.10