Add feature-deploy-on-ci task to Makefile for U/S CI
openshift-kni/cnf-features-deploy pull request #1356
Opened 2022-12-13 23:07 UTC by sshnaidm

One of jobs will need to deploy features, but not to run functest. It will run origin tests probably. Add a task that prepare for it.

2022-12-13 23:07 UTC, sshnaidm commented
/cc @SchSeba

2022-12-14 17:27 UTC, SchSeba commented on Makefile
> +feature-deploy-on-ci: setup-test-cluster setup-build-index-image feature-deploy feature-wait
we have `functests-on-ci` please change that one to 

functests-on-ci: feature-deploy-on-ci functests

so we can reuse

2022-12-14 20:15 UTC, nishant-parekh requested changes
@sshnaidm take a look at this script.. https://github.com/openshift-kni/cnf-features-deploy/blob/master/.githooks/commit-msg
I think you need to update the commit message to get past the prow/ci issue you are seeing..

2022-12-18 12:35 UTC, SchSeba approved these changes
/lgtm
/approve

2022-12-25 14:06 UTC, SchSeba commented
/override ci/prow/e2e-gcp-ovn

2022-12-25 14:08 UTC, sshnaidm commented
/cherry-pick release-4.12

2022-12-25 14:08 UTC, sshnaidm commented
/cherry-pick release-4.11

2022-12-25 14:08 UTC, sshnaidm commented
/cherry-pick release-4.10

2022-12-25 14:34 UTC, merged