updates Containerfile builder
openshift-kni/cnf-features-deploy pull request #2013
Opened 2024-08-28 17:45 UTC by rauhersu

2024-08-28 17:46 UTC, rauhersu commented
/hold

We need new Prow config working for master firstly

2024-08-28 18:29 UTC, nishant-parekh commented
please use `ztp:` in your commit message to fix the prow/ci job failing.

2024-08-28 18:31 UTC, nishant-parekh requested changes
update commit message

2024-08-29 09:53 UTC, rauhersu commented
> update commit message

Thanks @nishant-parekh , done !

2024-08-30 15:18 UTC, rauhersu commented
/unhold

2024-08-30 15:19 UTC, rauhersu commented
ping @nishant-parekh

2024-10-30 17:06 UTC, fontivan commented
Fixed in https://github.com/openshift-kni/cnf-features-deploy/pull/2092
@rauhersu this can be closed

2025-07-02 19:45 UTC, rauhersu commented
closed as per the previous comment

2025-07-02 19:45 UTC, closed without merging