CNF-14285: ztp: reference: Change "pod-security.kubernetes.io/" label to be prefix based
openshift-kni/cnf-features-deploy pull request #2051
Opened 2024-09-25 12:34 UTC by natifridman

2024-09-25 18:35 UTC, lack commented
Given that this is a better way, perhaps we should also remove my `allowLabels` and `requiredLabels` hacks too?

2024-09-25 18:39 UTC, lack commented
FYI: The commit log message must begin with `ztp:` and not `CNF-14285: ztp:` - It's fine for the PR to have the CNF-XXXX prefix, but not the git commit.

2024-09-26 06:57 UTC, natifridman commented
> Given that this is a better way, perhaps we should also remove my `allowLabels` and `requiredLabels` hacks too?

Removed `allowLabels`

2024-09-26 14:59 UTC, lack requested changes

2024-09-26 14:59 UTC, lack commented on ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionNS.yaml
>          "openshift.io/cluster-monitoring: \"true\""
We can also get rid of this `requiredLabels` template helper...  In fact, it may be easier to just revert 8ec2e880 entirely.

2024-09-26 15:26 UTC, lack commented on ztp/kube-compare-reference/metadata.yaml
> +        isPrefix: true
There's a little more we can remove: Look for every other `pod-security.kubernetes.io` in this section:
(line 187 and line 193 can be delete too)

2024-09-30 15:46 UTC, lack approved these changes

2024-09-30 15:46 UTC, lack commented
/approve

2024-09-30 15:50 UTC, merged