ztp: Create CRD for PolicyGenTemplate
openshift-kni/cnf-features-deploy pull request #643
Opened 2021-08-04 20:46 UTC by imiller0

Add a CRD for PolicyGenTemplate and update the policyGen tool to account
for changes in data types required.

Signed-off-by: Ian Miller <imiller@redhat.com>

2021-08-10 10:19 UTC, serngawy requested changes

2021-08-10 10:19 UTC, serngawy commented on ztp/gitops-subscriptions/argocd/policygentemplate-crd.yaml
> +apiVersion: apiextensions.k8s.io/v1
This file should be under cnf-feature-deploy/ztp/ran-site-plan-crd

2021-08-16 12:55 UTC, imiller0 commented
/retest

2021-08-19 12:12 UTC, imiller0 commented
Will resubmit this change with other work under a different PR

2021-08-19 12:12 UTC, closed without merging