ztp: Support complianceType for full PGT
openshift-kni/cnf-features-deploy pull request #815
Opened 2021-11-24 13:34 UTC by imiller0

Give the user control over the complianceType for all CRs in a
PolicyGenTemplate. This will ease the switch to "musthave" for all
policies which is required to limit CPU use on the managed cluster. The
difference in CPU use for managing mustonlyhave policies for the current
feature set is ~0.8 cpu as measured by the prometheus query:
sum(pod:container_cpu_usage:sum{namespace=~"openshift-logging|openshift-authentication-operator|openshift-kube-controller-manager|openshift-kube-apiserver|openshift-apiserver|open-cluster-management-agent|open-cluster-management-agent-addon"})

Signed-off-by: Ian Miller <imiller@redhat.com>

2021-11-24 14:55 UTC, imiller0 commented
/hold

2021-11-24 18:11 UTC, Missxiaoguo commented on ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
> +  complianceType: musthave
I am thinking probably more clear if we add this under something like "policyDefaults"? so a default remediationType can be added here as well.
spec:
  policyDefaults:
    complianceType: musthave

2021-11-25 19:00 UTC, serngawy requested changes

2021-11-29 21:44 UTC, imiller0 commented
/unhold

2021-11-30 00:48 UTC, serngawy approved these changes

2021-11-30 02:00 UTC, merged

2021-11-30 12:49 UTC, imiller0 commented
/cherry-pick release-4.9