ztp: Update Readme and examples
openshift-kni/cnf-features-deploy pull request #839
Opened 2021-12-06 20:00 UTC by serngawy

Signed-off-by: melserngawy <melserng@redhat.com>

2021-12-06 20:00 UTC, serngawy commented
/cc @imiller0

2021-12-06 20:00 UTC, serngawy commented
/cc @lack

2021-12-09 05:17 UTC, lack requested changes

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator-kustomize-plugin/README.md
> +The policy generator kustomize plugin consume the [policygenerator](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/policygenerator) lib and [PolicyGenTemplate](https://github.co
```suggestion
The policy generator kustomize plugin consumes the [policygenerator](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/policygenerator) library and [PolicyGenTemplate](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/ran-crd/policy-gen-template-crd.yaml) as a kustomize plugin. Kustomization.yaml is an example of how to use the policygenerator plugin.
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator-kustomize-plugin/README.md
> +After the build success `kustomize/` directory should be created with following tree
```suggestion
After the build succeeds, the `kustomize/` directory should be created with following structure:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator-kustomize-plugin/README.md
> +- Run the following command to dump the kusomization output to files under `out/` directory
```suggestion
- Run the following command to dump the kustomization output to files under the `out/` directory
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator-kustomize-plugin/README.md
> +- Run the following command to build policygenerator binary and create the kustomize plugin directory
```suggestion
- Run the following command to build the policygenerator binary and create the kustomize plugin directory structure:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +PolicyGen lib is used to facilitate creating ACM policies based on given CRs (custom resources) and [PolicyGenTemplate](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/ran-crd/po
```suggestion
The PolicyGen library is used to facilitate creating ACM policies based on a set of provided source CRs (custom resources) and [PolicyGenTemplate](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/ran-crd/policy-gen-template-crd.yaml) CRs which describe how to customize those source CRs.
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +List of the CRs that ztp RAN solution provide to deploy ACM policies are under the [ztp/source-crs](https://github.com/openshift-kni/cnf-features-deploy/tree/master/ztp/source-crs). PolicyGenTemplate
```suggestion
The full list of the CRs that ztp RAN solution provide to deploy ACM policies are under the [ztp/source-crs](https://github.com/openshift-kni/cnf-features-deploy/tree/master/ztp/source-crs). PolicyGenTemplate constructs the ACM policies by offering the following customization mechanisms:
```

And should we mention the source CRs are also embedded in our container image?

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +  1. Overlay; The given CRs that will be constructed into ACM policy could be override its attributes.
```suggestion
  1. Overlay: The given CRs that will be constructed into ACM policy may have some or all of their contents replaced by values specified in the PolicyGenTemplate.
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +  1. Grouping; Policies defined in the PolicyGenTemplate will be created under the same namespace AND share the PlacmentRules and PlacementBinding.
```suggestion
  1. Grouping: Policies defined in the PolicyGenTemplate will be created under the same namespace and share the same PlacmentRules and PlacementBinding.
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +- Example 1: considering the PolicyGenTemplate below to create ACM policy constructing [ConsoleOperatorDisable.yaml](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/Co
```suggestion
- Example 1: Consider the PolicyGenTemplate below to create ACM policies for both [ConsoleOperatorDisable.yaml](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/ConsoleOperatorDisable.yaml) and [ClusterLogging.yaml](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/ClusterLogging.yaml).
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +The placement binding and rules of the generated policies will be as below.
```suggestion
The placement binding and rules of the generated policies will be:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +The generated policies will be as below;
```suggestion
The generated policies will be:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +- Run the following command to build policygenerator binary
```suggestion
- Run the following command to build the policygenerator binary:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +- Run the following command to execute the unit test
```suggestion
- Run the following command to execute the unit tests:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +- Run the following command to see help
```suggestion
- Run the following command to see the command's help text:
```

2021-12-09 05:17 UTC, lack commented on ztp/policygenerator/README.md
> +- For using policygenerator library as kustomize plugin check the [policy-generator-kustomize-plugin](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/policygenerator-kustomize-pl
```suggestion
- For using policygenerator library as kustomize plugin, see [policy-generator-kustomize-plugin](https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/policygenerator-kustomize-plugin/README.md).
```

2021-12-09 21:10 UTC, serngawy commented on ztp/gitops-subscriptions/argocd/README.md
> +Check for `Status: Conditions:` it will show error logs ex; setting invalid `sourceFile->fileName:` will generate error.
done

2021-12-09 21:10 UTC, serngawy commented on ztp/gitops-subscriptions/argocd/README.md
> +Policy CRs are generated in same namespace as the PolicyGenTemplate from which they were created. The same troubleshooting flow applies to all policy CRs generated from PolicyGenTemplates regardless
done

2021-12-09 21:10 UTC, serngawy commented on ztp/gitops-subscriptions/argocd/README.md
> +If the Policies are not synchronized follow the steps below for failure to synchronize.
done

2021-12-09 21:12 UTC, serngawy commented on ztp/gitops-subscriptions/argocd/README.md
> +Check for `Status: Sync:` if there are log errors the `Sync: Status:` could be as below `Unknown` / `Error`.
Just to show the Sync->status is error or unknown as the Sync->condition show the logs

2021-12-10 14:51 UTC, serngawy commented
/retest

2021-12-15 17:43 UTC, lack approved these changes

2021-12-15 18:58 UTC, merged