ztp: Update the SiteConfig template language to be more go-template compatible
openshift-kni/cnf-features-deploy pull request #938
Opened 2022-02-02 14:18 UTC by lack

While this does not cut over to go templates yet, it does refactor the
templating language we use to be more future-proof and forward-facing,
given that customers can now override these templates.

Signed-off-by: Jim Ramsay <jramsay@redhat.com>

/cc @imiller0 @serngawy

2022-02-02 14:21 UTC, lack commented on ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
> +			key, err := translateTemplateKey(v.(string))
Here's the only change to the parsing logic!  That and the fairly simple (and well-tested) `translateTemplateKey` function below.

2022-02-03 20:59 UTC, lack commented
/retest

2022-02-04 10:42 UTC, lack commented
/retest

2022-02-04 12:09 UTC, lack commented
/retest

2022-02-08 13:57 UTC, lack commented
Testing shows that the siteconfig-generator output is identical before and after this change.

2022-02-08 18:15 UTC, serngawy requested changes
not sure what the benefits of changing the path but may be better to use go template and evaluate the use of it.

2022-02-08 19:46 UTC, lack commented
> not sure what the benefits of changing the path but may be better to use go template and evaluate the use of it.

The main benefit is that if/because we want to move to GoTemplate in the future, we can without affecting an user that's overriding the template.  We only get once chance to release the template format for the first time.

The reason I didn't go all the way to GoTemplate in this particular change was to minimize the change against 4.10.

2022-02-08 19:48 UTC, lack commented on ztp/siteconfig-generator/siteConfig/siteConfig.go
> +				}
This (and the following) replaces a potential 'panic' with proper error handling.

2022-02-10 15:01 UTC, imiller0 commented on ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
> +		input:          `top: { middle: { bottom: "{{ .Cluster.NoSuchKey }}" } }`,
Is the substitution relatively immune to whitespace as well? Might be good to add a few test cases like
`
key: "  {{ .Cluster.Name}}"
key: "{{ .Cluster.Name}}    "
key: "     {{ .Cluster.Name}}    "
`
etc

2022-02-10 15:33 UTC, merged