ztp: update Argocd patch
openshift-kni/cnf-features-deploy pull request #973
Opened 2022-02-16 19:23 UTC by serngawy

Signed-off-by: melserngawy <melserng@redhat.com>

2022-02-16 19:25 UTC, serngawy commented
/cc @lack

2022-02-17 13:32 UTC, lack requested changes

2022-02-17 14:10 UTC, serngawy commented on ztp/resource-generator/Containerfile
> -RUN microdnf install tar
done, put it back

2022-02-17 15:05 UTC, lack approved these changes

2022-02-21 15:05 UTC, merged

2022-02-24 13:22 UTC, serngawy commented
/cherry-pick release-4.10