ztp: PGT supports status updates or overlays
openshift-kni/cnf-features-deploy pull request #987
Opened 2022-03-01 14:21 UTC by nishant-parekh

Signed-off-by: Nishant Parekh <nparekh@redhat.com>

2022-03-01 16:54 UTC, nishant-parekh commented
/cc @Missxiaoguo @serngawy @imiller0 @vitus133

2022-03-01 17:00 UTC, serngawy requested changes
can we keep in sync the CRD as well https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/ran-crd/policy-gen-template-crd.yaml

2022-03-01 17:00 UTC, serngawy commented on ztp/policygenerator/policyGen/policyBuilder.go
> +		// If the user supplies a "spec" section but the source CR does not have
"status" not "spec"

2022-03-01 17:18 UTC, nishant-parekh commented on ztp/policygenerator/policyGen/policyBuilder.go
> +		// If the user supplies a "spec" section but the source CR does not have
updated

2022-03-01 17:18 UTC, nishant-parekh commented
> can we keep in sync the CRD as well https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/ran-crd/policy-gen-template-crd.yaml

synced with this change.

2022-03-01 19:17 UTC, nishant-parekh commented on ztp/ran-crd/policy-gen-template-crd.yaml
> +                            the sourceFile.status.
removed that section from the other two sections as well.

2022-03-02 17:12 UTC, imiller0 reviewed
/lgtm

2022-03-02 17:14 UTC, merged

2022-03-03 03:03 UTC, nishant-parekh commented
/cherry-pick release-4.10